(ns clara.miss-manners.manners-data)

(def manners-8-guest-facts
  [{:fact/type :party/guest-data :name "n1" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n1" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n2" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n2" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n3" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n3" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n3" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n4" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n4" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n5" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n5" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n5" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n6" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n6" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n6" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n7" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n7" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n8" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n8" :sex "m" :hobby "h1"}
   {:fact/type :party/seats-data :size 8}])

(def manners-16-guest-facts
  [{:fact/type :party/guest-data :name "n1" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n1" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n1" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n2" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n2" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n3" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n3" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n4" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n4" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n5" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n5" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n6" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n6" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n7" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n7" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n7" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n8" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n8" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n9" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n9" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n9" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n10" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n10" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n11" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n11" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n11" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n12" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n12" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n13" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n13" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n13" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n14" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n14" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n15" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n15" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n15" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n16" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n16" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n16" :sex "f" :hobby "h1"}
   {:fact/type :party/seats-data :size 16}])

(def manners-32-guest-facts
  [{:fact/type :party/guest-data :name "n1" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n1" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n2" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n2" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n2" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n3" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n3" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n4" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n4" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n5" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n5" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n6" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n6" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n6" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n7" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n7" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n7" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n8" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n8" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n8" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n9" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n9" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n9" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n10" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n10" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n11" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n11" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n12" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n12" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n13" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n13" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n14" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n14" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n15" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n15" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n15" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n16" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n16" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n16" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n17" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n17" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n18" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n18" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n19" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n19" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n19" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n20" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n20" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n20" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n21" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n21" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n21" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n22" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n22" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n22" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n23" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n23" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n23" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n24" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n24" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n25" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n25" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n25" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n26" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "n26" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "n26" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "n27" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n27" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n27" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n28" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n28" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n29" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n29" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n29" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n30" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n30" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n30" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n31" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "n31" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n32" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "n32" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "n32" :sex "m" :hobby "h2"}
   {:fact/type :party/seats-data :size 32}])

(def manners-128-guest-facts
  [{:fact/type :party/guest-data :name "1" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "1" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "1" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "1" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "1" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "2" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "2" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "2" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "2" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "2" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "3" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "3" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "3" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "4" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "4" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "4" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "4" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "5" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "5" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "5" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "6" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "6" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "6" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "6" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "6" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "7" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "7" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "7" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "7" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "8" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "8" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "9" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "9" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "9" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "9" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "10" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "10" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "10" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "10" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "10" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "11" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "11" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "11" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "11" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "12" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "12" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "12" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "13" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "13" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "14" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "14" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "14" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "14" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "15" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "15" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "15" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "15" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "15" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "16" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "16" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "16" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "17" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "17" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "18" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "18" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "18" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "18" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "19" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "19" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "20" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "20" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "21" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "21" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "21" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "21" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "22" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "22" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "22" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "23" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "23" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "23" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "24" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "24" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "24" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "24" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "24" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "25" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "25" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "26" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "26" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "27" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "27" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "27" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "28" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "28" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "28" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "28" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "28" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "29" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "29" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "30" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "30" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "31" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "31" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "31" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "32" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "32" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "32" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "33" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "33" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "34" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "34" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "34" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "35" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "35" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "35" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "35" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "35" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "36" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "36" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "36" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "36" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "37" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "37" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "37" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "38" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "38" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "38" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "38" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "39" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "39" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "40" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "40" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "41" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "41" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "42" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "42" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "43" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "43" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "43" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "44" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "44" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "44" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "44" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "45" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "45" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "46" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "46" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "46" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "47" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "47" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "47" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "48" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "48" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "49" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "49" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "49" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "49" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "49" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "50" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "50" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "50" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "51" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "51" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "51" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "51" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "52" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "52" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "52" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "52" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "53" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "53" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "53" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "53" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "53" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "54" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "54" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "55" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "55" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "56" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "56" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "57" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "57" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "57" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "58" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "58" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "58" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "58" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "58" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "59" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "59" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "59" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "60" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "60" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "60" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "60" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "61" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "61" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "61" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "61" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "62" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "62" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "62" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "62" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "62" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "63" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "63" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "63" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "63" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "63" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "64" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "64" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "64" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "64" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "64" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "65" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "65" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "65" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "65" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "65" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "66" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "66" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "66" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "67" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "67" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "68" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "68" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "68" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "68" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "69" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "69" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "69" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "70" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "70" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "70" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "70" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "70" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "71" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "71" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "71" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "72" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "72" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "72" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "73" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "73" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "73" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "74" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "74" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "74" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "74" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "74" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "75" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "75" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "76" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "76" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "76" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "76" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "76" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "77" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "77" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "78" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "78" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "79" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "79" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "79" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "79" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "79" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "80" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "80" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "80" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "80" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "81" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "81" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "82" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "82" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "82" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "82" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "82" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "83" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "83" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "83" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "84" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "84" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "85" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "85" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "86" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "86" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "87" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "87" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "87" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "87" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "88" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "88" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "88" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "88" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "88" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "89" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "89" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "89" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "89" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "90" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "90" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "90" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "91" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "91" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "91" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "91" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "91" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "92" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "92" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "92" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "92" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "93" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "93" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "93" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "94" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "94" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "95" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "95" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "96" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "96" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "96" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "96" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "96" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "97" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "97" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "97" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "98" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "98" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "99" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "99" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "100" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "100" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "100" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "100" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "101" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "101" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "101" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "101" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "101" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "102" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "102" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "102" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "102" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "102" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "103" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "103" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "103" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "103" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "103" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "104" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "104" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "104" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "104" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "104" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "105" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "105" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "106" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "106" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "106" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "107" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "107" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "107" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "107" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "107" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "108" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "108" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "108" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "108" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "108" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "109" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "109" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "110" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "110" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "110" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "110" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "111" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "111" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "112" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "112" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "112" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "112" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "112" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "113" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "113" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "113" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "113" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "114" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "114" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "115" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "115" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "115" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "115" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "116" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "116" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "116" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "116" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "117" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "117" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "117" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "118" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "118" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "118" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "119" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "119" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "120" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "120" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "120" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "120" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "120" :sex "m" :hobby "h4"}
   {:fact/type :party/guest-data :name "121" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "121" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "121" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "121" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "122" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "122" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "122" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "123" :sex "m" :hobby "h2"}
   {:fact/type :party/guest-data :name "123" :sex "m" :hobby "h3"}
   {:fact/type :party/guest-data :name "123" :sex "m" :hobby "h1"}
   {:fact/type :party/guest-data :name "123" :sex "m" :hobby "h5"}
   {:fact/type :party/guest-data :name "124" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "124" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "124" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "125" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "125" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "125" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "125" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "126" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "126" :sex "f" :hobby "h3"}
   {:fact/type :party/guest-data :name "126" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "126" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "127" :sex "f" :hobby "h5"}
   {:fact/type :party/guest-data :name "127" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "128" :sex "f" :hobby "h2"}
   {:fact/type :party/guest-data :name "128" :sex "f" :hobby "h4"}
   {:fact/type :party/guest-data :name "128" :sex "f" :hobby "h1"}
   {:fact/type :party/guest-data :name "128" :sex "f" :hobby "h3"}
   {:fact/type :party/seats-data :size 128}])
