name: Clojure CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

env:
  CLOJURE_CLI_VERSION: '1.12.5.1664'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: '22.3.1'
        java-version: '11'
        components: 'native-image'
        github-token: ${{secrets.GITHUB_TOKEN}}
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@13.6.1
      with:
        cli: ${{env.CLOJURE_CLI_VERSION}}
    - name: Cache Clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{runner.os}}-${{hashFiles('deps.edn')}}
        restore-keys: cljdeps-${{runner.os}}-
    - name: Run tests
      run: make test
    - name: Run coverage tests
      run: make test-coverage
    - name: Run generative tests
      run: make test-generative
    - name: Run clj-kondo linter
      run: make lint
    - name: Run build jar
      run: make build
    - name: Run build app
      run: |
        make build-native
        build/clara-test-app this is a test invocation of native app
